-- luacheck: globals describe it assert
local Ndjson = require("99.ndjson")
local eq = assert.are.same

describe("ndjson", function()
  it("decodes a whole line in one chunk", function()
    local decoder = Ndjson.new()
    local events = decoder:feed('{"a":1}\n')
    eq({ { a = 1 } }, events)
    eq("", decoder.buffer)
    eq(0, decoder.dropped)
  end)

  it("decodes one json object split across three chunks", function()
    local decoder = Ndjson.new()
    eq({}, decoder:feed('{"a":'))
    eq({}, decoder:feed("1,"))
    local events = decoder:feed('"b":2}\n')
    eq({ { a = 1, b = 2 } }, events)
    eq(0, decoder.dropped)
  end)

  it("decodes multiple objects in one chunk", function()
    local decoder = Ndjson.new()
    local events = decoder:feed('{"a":1}\n{"b":2}\n')
    eq({ { a = 1 }, { b = 2 } }, events)
    eq(0, decoder.dropped)
  end)

  it("handles interleaved partial and complete lines", function()
    local decoder = Ndjson.new()
    eq({ { a = 1 } }, decoder:feed('{"a":1}\n{"b":'))
    eq({ { b = 2 } }, decoder:feed("2}\n"))
    eq({ { c = 3 } }, decoder:feed('{"c":3}\n'))
    eq(0, decoder.dropped)
  end)

  it("drops invalid json and continues decoding later lines", function()
    local decoder = Ndjson.new()
    local events = decoder:feed('not json\n{"ok":true}\n')
    eq({ { ok = true } }, events)
    eq(1, decoder.dropped)
  end)

  it("flush decodes trailing un-terminated line", function()
    local decoder = Ndjson.new()
    eq({}, decoder:feed('{"a":1}'))
    local events = decoder:flush()
    eq({ { a = 1 } }, events)
    eq("", decoder.buffer)
  end)

  it("ignores empty lines without counting them as dropped", function()
    local decoder = Ndjson.new()
    local events = decoder:feed('\n  \n{"a":1}\n\n')
    eq({ { a = 1 } }, events)
    eq(0, decoder.dropped)
  end)
end)
